[build-system]
requires = ["setuptools >= 61.0.0", "oldest-supported-numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "beat"
version = "2.0.1"
requires-python = ">=3.9"
license = {text = "GPLv3"}
description = "'Bayesian Earthquake Analysis Tool'"
readme = "README.md"
authors = [
  {name = "Hannes Vasyura-Bathke", email = "vasbath@gfz-potsdam.de"}
]
maintainers = [
  {name = "Hannes Vasyura-Bathke", email = "vasbath@gfz-potsdam.de"}
]
keywords = ["Bayesian Inference", "seismology", "geodesy", "earthquake", "volcano"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: C",
    "Operating System :: POSIX",
    "Operating System :: MacOS"
]
dependencies = [
    "numpy",
    "scipy",
    "pytensor>=2.18.4",
    "pymc>=5.10.0",
    "tqdm>=4.64.0",
    "matplotlib>=3.1.1",
    "psutil>=5.9.0",
    "pyrocko>=2023.10.11"
]

[project.urls]
Home = "https://pyrocko.org/beat"
GitHub = "https://github.com/hvasbath/beat"
Issues = "https://github.com/hvasbath/beat/issues"

[project.optional-dependencies]
formatting = ["flake8", "ruff"]

[project.scripts]
beat = "beat.apps.beat:main"
beatdown = "beat.apps.beatdown:main"

[tool.setuptools.package-data]
beat = ["*.jpg", "*.png"]

[tool.setuptools]
packages=[
    "beat",
    "beat.fast_sweeping",
    "beat.voronoi",
    "beat.sampler",
    "beat.models",
    "beat.plotting",
    "beat.ffi",
    "beat.apps"
]
